import localFont from "next/font/local";
import "./globals.css";
import Aside from "@/components/Aside/Aside.jsx";
import StoreProvider from "@/app/StoreProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Crm Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex bg-gray-100`}
        >
          <Aside />
          {children}
        </body>
      </StoreProvider>
    </html>
  );
}
